### ISSUE TITLE
Window size on Linux is to big

### ISSUE THREAD

**Issue by agguro** [mich-w/QtSerialMonitor#3]
Is there a property that I can/need to modify to not have a screen width of 1910 ?  For now I can't manage to do it because the values resets to the old ones.

**Comment by mich-w** [comment]
I just added (actually uncommented) window size to be saved with the rest of the settings and reapplied when the app starts. I forgot why I disabled it in the first place, seems to work fine under Linux on my side (KDE Plasma).

**Comment by agguro** [comment]
That must be the problem here.  The size of the window remains and renders your application un-useful here :(, unfortunately for me.

**Comment by mich-w** [comment]
Could you please check if the latest build improves the mentioned behavior in any way ?

**Comment by agguro** [comment]
I will later when I am at home.

A terça, 25/01/2022, 11:42, Michał Waliszkiewicz ***@***.***>
escreveu:

**Comment by agguro** [comment]
The problem is gone with Linux Mint.
However you should add :
QMAKE_LFLAGS_RELEASE += -no-pie
QMAKE_LFLAGS_DEBUG += -no-pie -O0
to the .pro file so that the program is recognized as executable instead of a library (Linux Mint)
Thanks a lot, I will promote this tool on my website (not the source, just mentioning if it is ok by you?)

**Comment by mich-w** [comment]
About the "-no-pie" flag. Judging by the forums I think it might be something platform specific namely Debian based distros. Here on my side (Manjaro KDE) it seems to compile as an app binary by default. But sure, I will add it these lines. It doesn't seem to break anything so its all green right? :P

Feel free to mention the app, I appreciate that someone else found it useful.

**Comment by agguro** [comment]
on Ubuntu and Debian (it's the same) it doesn't brake anything.
